---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: .codeclimate.eslintrc
      extensions:
        - .js
  fixme:
    enabled: true
ratings:
  paths:
    - "**.inc"
    - "**.js"
    - "**.vue"
    - "**.scss"
    - "**.tpl"
    - "**.md"
    - "**.json"
    - "**.html"
exclude_paths:
  - dist/
  - test/
  - build/
  - src/store/modules/filters/masterdata/*
