/**
 * Masterdata for model types
 */
export const model = {
	type: 'multi-search',
	label: 'filters.masterdata.model.label',
	key: 'model',
	options: {
		// abarth
		'abarth': [{
			value: '124',
			label: '124',
			total: 0
		}, {
			value: '500',
			label: '500',
			total: 0
		}, {
			value: '595',
			label: '595',
			total: 0
		}, {
			value: 'punto',
			label: 'Punto',
			total: 0
		}],
		// alfa+romeo
		'alfa+romeo': [{
			value: '145',
			label: '145',
			total: 0
		}, {
			value: '146',
			label: '146',
			total: 0
		}, {
			value: '147',
			label: '147',
			total: 0
		}, {
			value: '155',
			label: '155',
			total: 0
		}, {
			value: '156',
			label: '156',
			total: 0
		}, {
			value: '159',
			label: '159',
			total: 0
		}, {
			value: '164',
			label: '164',
			total: 0
		}, {
			value: '166',
			label: '166',
			total: 0
		}, {
			value: '33',
			label: '33',
			total: 0
		}, {
			value: '4c',
			label: '4C',
			total: 0
		}, {
			value: '75',
			label: '75',
			total: 0
		}, {
			value: 'brera',
			label: 'Brera',
			total: 0
		}, {
			value: 'giulia',
			label: 'Giulia',
			total: 0
		}, {
			value: 'giulietta',
			label: 'Giulietta',
			total: 0
		}, {
			value: 'gt',
			label: 'GT',
			total: 0
		}, {
			value: 'gtv',
			label: 'GTV',
			total: 0
		}, {
			value: 'mito',
			label: 'MiTo',
			total: 0
		}, {
			value: 'spider',
			label: 'Spider',
			total: 0
		}],
		// aston+martin
		'aston+martin': [{
			value: 'cygnet',
			label: 'Cygnet',
			total: 0
		}, {
			value: 'db11',
			label: 'DB11',
			total: 0
		}, {
			value: 'db7',
			label: 'DB7',
			total: 0
		}, {
			value: 'db9',
			label: 'DB9',
			total: 0
		}, {
			value: 'dbs',
			label: 'DBS',
			total: 0
		}, {
			value: 'rapide',
			label: 'Rapide',
			total: 0
		}, {
			value: 'vanquish',
			label: 'Vanquish',
			total: 0
		}, {
			value: 'vantage',
			label: 'Vantage',
			total: 0
		}],
		// audi
		'audi': [{
			value: '100',
			label: '100',
			total: 0
		}, {
			value: '80',
			label: '80',
			total: 0
		}, {
			value: '90',
			label: '90',
			total: 0
		}, {
			value: 'a1',
			label: 'A1',
			total: 0
		}, {
			value: 'a2',
			label: 'A2',
			total: 0
		}, {
			value: 'a3',
			label: 'A3',
			total: 0
		}, {
			value: 'a4',
			label: 'A4',
			total: 0
		}, {
			value: 'a5',
			label: 'A5',
			total: 0
		}, {
			value: 'a6',
			label: 'A6',
			total: 0
		}, {
			value: 'a7',
			label: 'A7',
			total: 0
		}, {
			value: 'a8',
			label: 'A8',
			total: 0
		}, {
			value: 'cabriolet',
			label: 'Cabriolet',
			total: 0
		}, {
			value: 'coupe',
			label: 'Coupé',
			total: 0
		}, {
			value: 'q2',
			label: 'Q2',
			total: 0
		}, {
			value: 'q3',
			label: 'Q3',
			total: 0
		}, {
			value: 'q5',
			label: 'Q5',
			total: 0
		}, {
			value: 'q7',
			label: 'Q7',
			total: 0
		}, {
			value: 'r8',
			label: 'R8',
			total: 0
		}, {
			value: 'tt',
			label: 'TT',
			total: 0
		}],
		// bentley
		'bentley': [{
			value: 'arnage',
			label: 'Arnage',
			total: 0
		}, {
			value: 'bentayga',
			label: 'Bentayga',
			total: 0
		}, {
			value: 'continental',
			label: 'Continental',
			total: 0
		}, {
			value: 'flying+spur',
			label: 'Flying Spur',
			total: 0
		}, {
			value: 'mulsanne',
			label: 'Mulsanne',
			total: 0
		}],
		// bmw
		'bmw': [{
			value: '1-serie',
			label: '1-serie',
			total: 0
		}, {
			value: '2-serie',
			label: '2-serie',
			total: 0
		}, {
			value: '3-serie',
			label: '3-serie',
			total: 0
		}, {
			value: '4-serie',
			label: '4-serie',
			total: 0
		}, {
			value: '5-serie',
			label: '5-serie',
			total: 0
		}, {
			value: '6-serie',
			label: '6-serie',
			total: 0
		}, {
			value: '7-serie',
			label: '7-serie',
			total: 0
		}, {
			value: '8-serie',
			label: '8-serie',
			total: 0
		}, {
			value: 'i3',
			label: 'i3',
			total: 0
		}, {
			value: 'i8',
			label: 'i8',
			total: 0
		}, {
			value: 'x1',
			label: 'X1',
			total: 0
		}, {
			value: 'x3',
			label: 'X3',
			total: 0
		}, {
			value: 'x4',
			label: 'X4',
			total: 0
		}, {
			value: 'x5',
			label: 'X5',
			total: 0
		}, {
			value: 'x6',
			label: 'X6',
			total: 0
		}, {
			value: 'z3',
			label: 'Z3',
			total: 0
		}, {
			value: 'z4',
			label: 'Z4',
			total: 0
		}, {
			value: 'z8',
			label: 'Z8',
			total: 0
		}],
		// bugatti
		'bugatti': [{
			value: 'veyron',
			label: 'Veyron',
			total: 0
		}],
		// cadillac
		'cadillac': [{
			value: 'ats',
			label: 'ATS',
			total: 0
		}, {
			value: 'bls',
			label: 'BLS',
			total: 0
		}, {
			value: 'ct6',
			label: 'CT6',
			total: 0
		}, {
			value: 'cts',
			label: 'CTS',
			total: 0
		}, {
			value: 'eldorado',
			label: 'Eldorado',
			total: 0
		}, {
			value: 'escalade',
			label: 'Escalade',
			total: 0
		}, {
			value: 'seville',
			label: 'Seville',
			total: 0
		}, {
			value: 'srx',
			label: 'SRX',
			total: 0
		}, {
			value: 'sts',
			label: 'STS',
			total: 0
		}, {
			value: 'xlr',
			label: 'XLR',
			total: 0
		}, {
			value: 'xt5',
			label: 'XT5',
			total: 0
		}],
		// chevrolet
		'chevrolet': [{
			value: 'alero',
			label: 'Alero',
			total: 0
		}, {
			value: 'aveo',
			label: 'Aveo',
			total: 0
		}, {
			value: 'blazer',
			label: 'Blazer',
			total: 0
		}, {
			value: 'camaro',
			label: 'Camaro',
			total: 0
		}, {
			value: 'captiva',
			label: 'Captiva',
			total: 0
		}, {
			value: 'corvette',
			label: 'Corvette',
			total: 0
		}, {
			value: 'cruze',
			label: 'Cruze',
			total: 0
		}, {
			value: 'epica',
			label: 'Epica',
			total: 0
		}, {
			value: 'evanda',
			label: 'Evanda',
			total: 0
		}, {
			value: 'hhr',
			label: 'HHR',
			total: 0
		}, {
			value: 'kalos',
			label: 'Kalos',
			total: 0
		}, {
			value: 'lacetti',
			label: 'Lacetti',
			total: 0
		}, {
			value: 'matiz',
			label: 'Matiz',
			total: 0
		}, {
			value: 'nubira',
			label: 'Nubira',
			total: 0
		}, {
			value: 'orlando',
			label: 'Orlando',
			total: 0
		}, {
			value: 'spark',
			label: 'Spark',
			total: 0
		}, {
			value: 'tacuma',
			label: 'Tacuma',
			total: 0
		}, {
			value: 'trax',
			label: 'Trax',
			total: 0
		}, {
			value: 'volt',
			label: 'Volt',
			total: 0
		}],
		// chrysler
		'chrysler': [{
			value: '300c',
			label: '300C',
			total: 0
		}, {
			value: '300m',
			label: '300M',
			total: 0
		}, {
			value: 'crossfire',
			label: 'Crossfire',
			total: 0
		}, {
			value: 'grand+voyager',
			label: 'Grand Voyager',
			total: 0
		}, {
			value: 'neon',
			label: 'Neon',
			total: 0
		}, {
			value: 'new+yorker',
			label: 'New Yorker',
			total: 0
		}, {
			value: 'pt+cruiser',
			label: 'PT Cruiser',
			total: 0
		}, {
			value: 'sebring',
			label: 'Sebring',
			total: 0
		}, {
			value: 'stratus',
			label: 'Stratus',
			total: 0
		}, {
			value: 'viper',
			label: 'Viper',
			total: 0
		}, {
			value: 'vision',
			label: 'Vision',
			total: 0
		}, {
			value: 'voyager',
			label: 'Voyager',
			total: 0
		}],
		// citroen
		'citroen': [{
			value: '2cv',
			label: '2CV',
			total: 0
		}, {
			value: 'ax',
			label: 'AX',
			total: 0
		}, {
			value: 'berlingo',
			label: 'Berlingo',
			total: 0
		}, {
			value: 'bx',
			label: 'BX',
			total: 0
		}, {
			value: 'c-crosser',
			label: 'C-Crosser',
			total: 0
		}, {
			value: 'c-zero',
			label: 'C-Zero',
			total: 0
		}, {
			value: 'c1',
			label: 'C1',
			total: 0
		}, {
			value: 'c2',
			label: 'C2',
			total: 0
		}, {
			value: 'c3',
			label: 'C3',
			total: 0
		}, {
			value: 'c3+picasso',
			label: 'C3 Picasso',
			total: 0
		}, {
			value: 'c4',
			label: 'C4',
			total: 0
		}, {
			value: 'c4+aircross',
			label: 'C4 Aircross',
			total: 0
		}, {
			value: 'c4+cactus',
			label: 'C4 Cactus',
			total: 0
		}, {
			value: 'c4+picasso',
			label: 'C4 Picasso',
			total: 0
		}, {
			value: 'c5',
			label: 'C5',
			total: 0
		}, {
			value: 'c6',
			label: 'C6',
			total: 0
		}, {
			value: 'c8',
			label: 'C8',
			total: 0
		}, {
			value: 'cx',
			label: 'CX',
			total: 0
		}, {
			value: 'ds3',
			label: '',
			total: 0
		}, {
			value: 'ds4',
			label: '',
			total: 0
		}, {
			value: 'ds5',
			label: '',
			total: 0
		}, {
			value: 'evasion',
			label: 'Evasion',
			total: 0
		}, {
			value: 'jumper',
			label: 'Jumper',
			total: 0
		}, {
			value: 'jumpy',
			label: 'Jumpy',
			total: 0
		}, {
			value: 'nemo',
			label: 'Nemo',
			total: 0
		}, {
			value: 'saxo',
			label: 'Saxo',
			total: 0
		}, {
			value: 'xantia',
			label: 'Xantia',
			total: 0
		}, {
			value: 'xm',
			label: 'XM',
			total: 0
		}, {
			value: 'xsara',
			label: 'Xsara',
			total: 0
		}, {
			value: 'xsara+picasso',
			label: 'Xsara Picasso',
			total: 0
		}, {
			value: 'zx',
			label: 'ZX',
			total: 0
		}],
		// dacia
		'dacia': [{
			value: 'dokker',
			label: 'Dokker',
			total: 0
		}, {
			value: 'duster',
			label: 'Duster',
			total: 0
		}, {
			value: 'lodgy',
			label: 'Lodgy',
			total: 0
		}, {
			value: 'logan',
			label: 'Logan',
			total: 0
		}, {
			value: 'sandero',
			label: 'Sandero',
			total: 0
		}],
		// daewoo
		'daewoo': [{
			value: 'espero',
			label: 'Espero',
			total: 0
		}, {
			value: 'evanda',
			label: 'Evanda',
			total: 0
		}, {
			value: 'kalos',
			label: 'Kalos',
			total: 0
		}, {
			value: 'lacetti',
			label: 'Lacetti',
			total: 0
		}, {
			value: 'lanos',
			label: 'Lanos',
			total: 0
		}, {
			value: 'leganza',
			label: 'Leganza',
			total: 0
		}, {
			value: 'matiz',
			label: 'Matiz',
			total: 0
		}, {
			value: 'nexia',
			label: 'Nexia',
			total: 0
		}, {
			value: 'nubira',
			label: 'Nubira',
			total: 0
		}, {
			value: 'tacuma',
			label: 'Tacuma',
			total: 0
		}],
		// daihatsu
		'daihatsu': [{
			value: 'applause',
			label: 'Applause',
			total: 0
		}, {
			value: 'charade',
			label: 'Charade',
			total: 0
		}, {
			value: 'copen',
			label: 'Copen',
			total: 0
		}, {
			value: 'cuore',
			label: 'Cuore',
			total: 0
		}, {
			value: 'feroza',
			label: 'Feroza',
			total: 0
		}, {
			value: 'gran+move',
			label: 'Gran Move',
			total: 0
		}, {
			value: 'materia',
			label: 'Materia',
			total: 0
		}, {
			value: 'move',
			label: 'Move',
			total: 0
		}, {
			value: 'rocky',
			label: 'Rocky',
			total: 0
		}, {
			value: 'sirion',
			label: 'Sirion',
			total: 0
		}, {
			value: 'terios',
			label: 'Terios',
			total: 0
		}, {
			value: 'trevis',
			label: 'Trevis',
			total: 0
		}, {
			value: 'valera',
			label: 'Valéra',
			total: 0
		}, {
			value: 'young+rv',
			label: 'Young RV',
			total: 0
		}],
		// dodge
		'dodge': [{
			value: 'avenger',
			label: 'Avenger',
			total: 0
		}, {
			value: 'caliber',
			label: 'Caliber',
			total: 0
		}, {
			value: 'journey',
			label: 'Journey',
			total: 0
		}, {
			value: 'nitro',
			label: 'Nitro',
			total: 0
		}, {
			value: 'viper',
			label: 'Viper',
			total: 0
		}],
		// donkervoort
		'donkervoort': [{
			value: 'd8',
			label: 'D8',
			total: 0
		}, {
			value: 'd8+gto',
			label: 'D8 GTO',
			total: 0
		}],
		// ds
		'ds': [{
			value: '3',
			label: '3',
			total: 0
		}, {
			value: '4',
			label: '4',
			total: 0
		}, {
			value: '5',
			label: '5',
			total: 0
		}],
		// ferrari
		'ferrari': [{
			value: '348',
			label: '348',
			total: 0
		}, {
			value: '360',
			label: '360',
			total: 0
		}, {
			value: '456',
			label: '456',
			total: 0
		}, {
			value: '458',
			label: '458',
			total: 0
		}, {
			value: '488',
			label: '488',
			total: 0
		}, {
			value: '550',
			label: '550',
			total: 0
		}, {
			value: '575m',
			label: '575M',
			total: 0
		}, {
			value: '599',
			label: '599',
			total: 0
		}, {
			value: '612',
			label: '612',
			total: 0
		}, {
			value: 'california',
			label: 'California',
			total: 0
		}, {
			value: 'enzo',
			label: 'Enzo',
			total: 0
		}, {
			value: 'f12',
			label: 'F12',
			total: 0
		}, {
			value: 'f355',
			label: 'F355',
			total: 0
		}, {
			value: 'f430',
			label: 'F430',
			total: 0
		}, {
			value: 'ff',
			label: 'FF',
			total: 0
		}, {
			value: 'gtc4',
			label: 'GTC4',
			total: 0
		}],
		// fiat
		'fiat': [{
			value: '500',
			label: '500',
			total: 0
		}, {
			value: '500l',
			label: '500L',
			total: 0
		}, {
			value: '500x',
			label: '500X',
			total: 0
		}, {
			value: '600',
			label: '600',
			total: 0
		}, {
			value: 'barchetta',
			label: 'Barchetta',
			total: 0
		}, {
			value: 'brava',
			label: 'Brava',
			total: 0
		}, {
			value: 'bravo',
			label: 'Bravo',
			total: 0
		}, {
			value: 'cinquecento',
			label: 'Cinquecento',
			total: 0
		}, {
			value: 'coupe',
			label: 'Coupé',
			total: 0
		}, {
			value: 'croma',
			label: 'Croma',
			total: 0
		}, {
			value: 'doblo',
			label: 'Doblò',
			total: 0
		}, {
			value: 'ducato',
			label: 'Ducato',
			total: 0
		}, {
			value: 'fiorino',
			label: 'Fiorino',
			total: 0
		}, {
			value: 'idea',
			label: 'Idea',
			total: 0
		}, {
			value: 'marea',
			label: 'Marea',
			total: 0
		}, {
			value: 'multipla',
			label: 'Multipla',
			total: 0
		}, {
			value: 'palio',
			label: 'Palio',
			total: 0
		}, {
			value: 'panda',
			label: 'Panda',
			total: 0
		}, {
			value: 'punto',
			label: 'Punto',
			total: 0
		}, {
			value: 'qubo',
			label: 'Qubo',
			total: 0
		}, {
			value: 'scudo',
			label: 'Scudo',
			total: 0
		}, {
			value: 'sedici',
			label: 'Sedici',
			total: 0
		}, {
			value: 'seicento',
			label: 'Seicento',
			total: 0
		}, {
			value: 'stilo',
			label: 'Stilo',
			total: 0
		}, {
			value: 'strada',
			label: 'Strada',
			total: 0
		}, {
			value: 'talento',
			label: 'Talento',
			total: 0
		}, {
			value: 'tempra',
			label: 'Tempra',
			total: 0
		}, {
			value: 'tipo',
			label: 'Tipo',
			total: 0
		}, {
			value: 'ulysse',
			label: 'Ulysse',
			total: 0
		}, {
			value: 'uno',
			label: 'Uno',
			total: 0
		}],
		// fisker
		'fisker': [{
			value: 'karma',
			label: 'Karma',
			total: 0
		}],
		// ford
		'ford': [{
			value: 'b-max',
			label: 'B-MAX',
			total: 0
		}, {
			value: 'c-max',
			label: 'C-MAX',
			total: 0
		}, {
			value: 'cougar',
			label: 'Cougar',
			total: 0
		}, {
			value: 'ecosport',
			label: 'Ecosport',
			total: 0
		}, {
			value: 'edge',
			label: 'Edge',
			total: 0
		}, {
			value: 'escort',
			label: 'Escort',
			total: 0
		}, {
			value: 'expedition',
			label: 'Expedition',
			total: 0
		}, {
			value: 'explorer',
			label: 'Explorer',
			total: 0
		}, {
			value: 'fiesta',
			label: 'Fiesta',
			total: 0
		}, {
			value: 'focus',
			label: 'Focus',
			total: 0
		}, {
			value: 'focus+c-max',
			label: 'Focus C-Max',
			total: 0
		}, {
			value: 'fusion',
			label: 'Fusion',
			total: 0
		}, {
			value: 'galaxy',
			label: 'Galaxy',
			total: 0
		}, {
			value: 'ka',
			label: 'Ka',
			total: 0
		}, {
			value: 'kuga',
			label: 'Kuga',
			total: 0
		}, {
			value: 'mondeo',
			label: 'Mondeo',
			total: 0
		}, {
			value: 'mustang',
			label: 'Mustang',
			total: 0
		}, {
			value: 'orion',
			label: 'Orion',
			total: 0
		}, {
			value: 'puma',
			label: 'Puma',
			total: 0
		}, {
			value: 'ranger',
			label: 'Ranger',
			total: 0
		}, {
			value: 's-max',
			label: 'S-MAX',
			total: 0
		}, {
			value: 'scorpio',
			label: 'Scorpio',
			total: 0
		}, {
			value: 'sierra',
			label: 'Sierra',
			total: 0
		}, {
			value: 'taurus',
			label: 'Taurus',
			total: 0
		}, {
			value: 'thunderbird',
			label: 'Thunderbird',
			total: 0
		}, {
			value: 'tourneo',
			label: 'Tourneo',
			total: 0
		}, {
			value: 'tourneo+connect',
			label: 'Tourneo Connect',
			total: 0
		}, {
			value: 'tourneo+courier',
			label: 'Tourneo Courier',
			total: 0
		}, {
			value: 'tourneo+custom',
			label: 'Tourneo Custom',
			total: 0
		}, {
			value: 'transit+connect',
			label: 'Transit Connect',
			total: 0
		}, {
			value: 'windstar',
			label: 'Windstar',
			total: 0
		}],
		// honda
		'honda': [{
			value: 'accord',
			label: 'Accord',
			total: 0
		}, {
			value: 'civic',
			label: 'Civic',
			total: 0
		}, {
			value: 'concerto',
			label: 'Concerto',
			total: 0
		}, {
			value: 'cr-v',
			label: 'CR-V',
			total: 0
		}, {
			value: 'cr-z',
			label: 'CR-Z',
			total: 0
		}, {
			value: 'crx',
			label: 'CRX',
			total: 0
		}, {
			value: 'fr-v',
			label: 'FR-V',
			total: 0
		}, {
			value: 'hr-v',
			label: 'HR-V',
			total: 0
		}, {
			value: 'insight',
			label: 'Insight',
			total: 0
		}, {
			value: 'jazz',
			label: 'Jazz',
			total: 0
		}, {
			value: 'legend',
			label: 'Legend',
			total: 0
		}, {
			value: 'logo',
			label: 'Logo',
			total: 0
		}, {
			value: 'nsx',
			label: 'NSX',
			total: 0
		}, {
			value: 'prelude',
			label: 'Prelude',
			total: 0
		}, {
			value: 's2000',
			label: 'S2000',
			total: 0
		}, {
			value: 'shuttle',
			label: 'Shuttle',
			total: 0
		}, {
			value: 'stream',
			label: 'Stream',
			total: 0
		}],
		// hummer
		'hummer': [{
			value: 'h2',
			label: 'H2',
			total: 0
		}, {
			value: 'h3',
			label: 'H3',
			total: 0
		}],
		// hyundai
		'hyundai': [{
			value: 'accent',
			label: 'Accent',
			total: 0
		}, {
			value: 'atos',
			label: 'Atos',
			total: 0
		}, {
			value: 'coupe',
			label: 'Coupé',
			total: 0
		}, {
			value: 'elantra',
			label: 'Elantra',
			total: 0
		}, {
			value: 'excel',
			label: 'Excel',
			total: 0
		}, {
			value: 'genesis',
			label: 'Genesis',
			total: 0
		}, {
			value: 'getz',
			label: 'Getz',
			total: 0
		}, {
			value: 'grandeur',
			label: 'Grandeur',
			total: 0
		}, {
			value: 'h300',
			label: 'H300',
			total: 0
		}, {
			value: 'i10',
			label: 'i10',
			total: 0
		}, {
			value: 'i20',
			label: 'i20',
			total: 0
		}, {
			value: 'i30',
			label: 'i30',
			total: 0
		}, {
			value: 'i40',
			label: 'i40',
			total: 0
		}, {
			value: 'ioniq',
			label: 'Ioniq',
			total: 0
		}, {
			value: 'ix20',
			label: 'ix20',
			total: 0
		}, {
			value: 'ix35',
			label: 'ix35',
			total: 0
		}, {
			value: 'lantra',
			label: 'Lantra',
			total: 0
		}, {
			value: 'matrix',
			label: 'Matrix',
			total: 0
		}, {
			value: 'pony',
			label: 'Pony',
			total: 0
		}, {
			value: 'santa+fe',
			label: 'Santa Fe',
			total: 0
		}, {
			value: 'scoupe',
			label: 'Scoupé',
			total: 0
		}, {
			value: 'sonata',
			label: 'Sonata',
			total: 0
		}, {
			value: 'terracan',
			label: 'Terracan',
			total: 0
		}, {
			value: 'trajet',
			label: 'Trajet',
			total: 0
		}, {
			value: 'tucson',
			label: 'Tucson',
			total: 0
		}, {
			value: 'veloster',
			label: 'Veloster',
			total: 0
		}, {
			value: 'xg',
			label: 'XG',
			total: 0
		}],
		// infiniti
		'infiniti': [{
			value: 'ex',
			label: 'EX',
			total: 0
		}, {
			value: 'fx',
			label: 'FX',
			total: 0
		}, {
			value: 'g',
			label: 'G',
			total: 0
		}, {
			value: 'm',
			label: 'M',
			total: 0
		}, {
			value: 'q30',
			label: 'Q30',
			total: 0
		}, {
			value: 'q50',
			label: 'Q50',
			total: 0
		}, {
			value: 'q60',
			label: 'Q60',
			total: 0
		}, {
			value: 'q70',
			label: 'Q70',
			total: 0
		}, {
			value: 'qx50',
			label: 'QX50',
			total: 0
		}, {
			value: 'qx70',
			label: 'QX70',
			total: 0
		}],
		// iveco
		'iveco': [{
			value: 'daily',
			label: 'Daily',
			total: 0
		}],
		// jaguar
		'jaguar': [{
			value: 'f-pace',
			label: 'F-Pace',
			total: 0
		}, {
			value: 'f-type',
			label: 'F-Type',
			total: 0
		}, {
			value: 's-type',
			label: 'S-Type',
			total: 0
		}, {
			value: 'x-type',
			label: 'X-Type',
			total: 0
		}, {
			value: 'xe',
			label: 'XE',
			total: 0
		}, {
			value: 'xf',
			label: 'XF',
			total: 0
		}, {
			value: 'xj',
			label: 'XJ',
			total: 0
		}, {
			value: 'xjs',
			label: 'XJS',
			total: 0
		}, {
			value: 'xk',
			label: 'XK',
			total: 0
		}],
		// jeep
		'jeep': [{
			value: 'cherokee',
			label: 'Cherokee',
			total: 0
		}, {
			value: 'commander',
			label: 'Commander',
			total: 0
		}, {
			value: 'compass',
			label: 'Compass',
			total: 0
		}, {
			value: 'grand+cherokee',
			label: 'Grand Cherokee',
			total: 0
		}, {
			value: 'patriot',
			label: 'Patriot',
			total: 0
		}, {
			value: 'renegade',
			label: 'Renegade',
			total: 0
		}, {
			value: 'wrangler',
			label: 'Wrangler',
			total: 0
		}],
		// kia
		'kia': [{
			value: 'carens',
			label: 'Carens',
			total: 0
		}, {
			value: 'carnival',
			label: 'Carnival',
			total: 0
		}, {
			value: 'ceed',
			label: 'Ceed',
			total: 0
		}, {
			value: 'cerato',
			label: 'Cerato',
			total: 0
		}, {
			value: 'clarus',
			label: 'Clarus',
			total: 0
		}, {
			value: 'joice',
			label: 'Joice',
			total: 0
		}, {
			value: 'magentis',
			label: 'Magentis',
			total: 0
		}, {
			value: 'mentor',
			label: 'Mentor',
			total: 0
		}, {
			value: 'niro',
			label: 'Niro',
			total: 0
		}, {
			value: 'opirus',
			label: 'Opirus',
			total: 0
		}, {
			value: 'optima',
			label: 'Optima',
			total: 0
		}, {
			value: 'picanto',
			label: 'Picanto',
			total: 0
		}, {
			value: 'pride',
			label: 'Pride',
			total: 0
		}, {
			value: 'rio',
			label: 'Rio',
			total: 0
		}, {
			value: 'sephia',
			label: 'Sephia',
			total: 0
		}, {
			value: 'shuma',
			label: 'Shuma',
			total: 0
		}, {
			value: 'sorento',
			label: 'Sorento',
			total: 0
		}, {
			value: 'soul',
			label: 'Soul',
			total: 0
		}, {
			value: 'sportage',
			label: 'Sportage',
			total: 0
		}, {
			value: 'venga',
			label: 'Venga',
			total: 0
		}],
		// lada
		'lada': [{
			value: '110',
			label: '110',
			total: 0
		}, {
			value: '111',
			label: '111',
			total: 0
		}, {
			value: '112',
			label: '112',
			total: 0
		}, {
			value: '2100-serie',
			label: '2100-serie',
			total: 0
		}, {
			value: 'kalina',
			label: 'Kalina',
			total: 0
		}, {
			value: 'niva',
			label: 'Niva',
			total: 0
		}, {
			value: 'priora',
			label: 'Priora',
			total: 0
		}, {
			value: 'samara',
			label: 'Samara',
			total: 0
		}],
		// lamborghini
		'lamborghini': [{
			value: 'aventador',
			label: 'Aventador',
			total: 0
		}, {
			value: 'diablo',
			label: 'Diablo',
			total: 0
		}, {
			value: 'gallardo',
			label: 'Gallardo',
			total: 0
		}, {
			value: 'huracan',
			label: 'Huracán',
			total: 0
		}, {
			value: 'murcielago',
			label: 'Murciélago',
			total: 0
		}],
		// lancia
		'lancia': [{
			value: 'dedra',
			label: 'Dedra',
			total: 0
		}, {
			value: 'delta',
			label: 'Delta',
			total: 0
		}, {
			value: 'flavia',
			label: 'Flavia',
			total: 0
		}, {
			value: 'kappa',
			label: 'Kappa',
			total: 0
		}, {
			value: 'lybra',
			label: 'Lybra',
			total: 0
		}, {
			value: 'musa',
			label: 'Musa',
			total: 0
		}, {
			value: 'phedra',
			label: 'Phedra',
			total: 0
		}, {
			value: 'thema',
			label: 'Thema',
			total: 0
		}, {
			value: 'thesis',
			label: 'Thesis',
			total: 0
		}, {
			value: 'voyager',
			label: 'Voyager',
			total: 0
		}, {
			value: 'ypsilon',
			label: 'Ypsilon',
			total: 0
		}, {
			value: 'zeta',
			label: 'Zeta',
			total: 0
		}],
		// land+rover
		'land+rover': [{
			value: 'defender',
			label: 'Defender',
			total: 0
		}, {
			value: 'discovery',
			label: 'Discovery',
			total: 0
		}, {
			value: 'discovery+sport',
			label: 'Discovery Sport',
			total: 0
		}, {
			value: 'freelander',
			label: 'Freelander',
			total: 0
		}, {
			value: 'range+rover',
			label: 'Range Rover',
			total: 0
		}, {
			value: 'range+rover+evoque',
			label: 'Evoque',
			total: 0
		}, {
			value: 'range+rover+sport',
			label: 'Range Rover Sport',
			total: 0
		}],
		// landwind
		'landwind': [{
			value: 'cv9',
			label: 'CV9',
			total: 0
		}],
		// lexus
		'lexus': [{
			value: 'ct',
			label: 'CT',
			total: 0
		}, {
			value: 'gs',
			label: 'GS',
			total: 0
		}, {
			value: 'is',
			label: 'IS',
			total: 0
		}, {
			value: 'ls',
			label: 'LS',
			total: 0
		}, {
			value: 'nx',
			label: 'NX',
			total: 0
		}, {
			value: 'rc',
			label: 'RC',
			total: 0
		}, {
			value: 'rx',
			label: 'RX',
			total: 0
		}, {
			value: 'sc',
			label: 'SC',
			total: 0
		}],
		// lotus
		'lotus': [{
			value: 'elise',
			label: 'Elise',
			total: 0
		}, {
			value: 'esprit',
			label: 'Esprit',
			total: 0
		}, {
			value: 'europa',
			label: 'Europa',
			total: 0
		}, {
			value: 'evora',
			label: 'Evora',
			total: 0
		}, {
			value: 'exige',
			label: 'Exige',
			total: 0
		}],
		// maserati
		'maserati': [{
			value: '3200+gt',
			label: '3200 GT',
			total: 0
		}, {
			value: 'coupe',
			label: 'Coupé',
			total: 0
		}, {
			value: 'ghibli',
			label: 'Ghibli',
			total: 0
		}, {
			value: 'grancabrio',
			label: 'GranCabrio',
			total: 0
		}, {
			value: 'granturismo',
			label: 'GranTurismo',
			total: 0
		}, {
			value: 'quattroporte',
			label: 'Quattroporte',
			total: 0
		}, {
			value: 'spyder',
			label: 'Spyder',
			total: 0
		}],
		// maybach
		'maybach': [{
			value: '57',
			label: '57',
			total: 0
		}, {
			value: '62',
			label: '62',
			total: 0
		}],
		// mazda
		'mazda': [{
			value: '121',
			label: '121',
			total: 0
		}, {
			value: '2',
			label: '2',
			total: 0
		}, {
			value: '3',
			label: '3',
			total: 0
		}, {
			value: '323',
			label: '323',
			total: 0
		}, {
			value: '5',
			label: '5',
			total: 0
		}, {
			value: '6',
			label: '6',
			total: 0
		}, {
			value: '626',
			label: '626',
			total: 0
		}, {
			value: 'cx-3',
			label: 'CX-3',
			total: 0
		}, {
			value: 'cx-5',
			label: 'CX-5',
			total: 0
		}, {
			value: 'cx-7',
			label: 'CX-7',
			total: 0
		}, {
			value: 'cx-9',
			label: 'CX-9',
			total: 0
		}, {
			value: 'demio',
			label: 'Demio',
			total: 0
		}, {
			value: 'mpv',
			label: 'MPV',
			total: 0
		}, {
			value: 'mx-3',
			label: 'MX-3',
			total: 0
		}, {
			value: 'mx-5',
			label: 'MX-5',
			total: 0
		}, {
			value: 'mx-6',
			label: 'MX-6',
			total: 0
		}, {
			value: 'premacy',
			label: 'Premacy',
			total: 0
		}, {
			value: 'rx-7',
			label: 'RX-7',
			total: 0
		}, {
			value: 'rx-8',
			label: 'RX-8',
			total: 0
		}, {
			value: 'tribute',
			label: 'Tribute',
			total: 0
		}, {
			value: 'xedos+6',
			label: 'Xedos 6',
			total: 0
		}, {
			value: 'xedos+9',
			label: 'Xedos 9',
			total: 0
		}],
		// mercedes-benz
		'mercedes-benz': [{
			value: '190-serie',
			label: '190-serie',
			total: 0
		}, {
			value: '200-serie',
			label: '200-serie',
			total: 0
		}, {
			value: 'a-klasse',
			label: 'A-klasse',
			total: 0
		}, {
			value: 'amg+gt',
			label: 'AMG GT',
			total: 0
		}, {
			value: 'b-klasse',
			label: 'B-klasse',
			total: 0
		}, {
			value: 'c-klasse',
			label: 'C-klasse',
			total: 0
		}, {
			value: 'citan',
			label: 'Citan',
			total: 0
		}, {
			value: 'cl-klasse',
			label: 'CL-klasse',
			total: 0
		}, {
			value: 'cla-klasse',
			label: 'CLA-klasse',
			total: 0
		}, {
			value: 'clc-klasse',
			label: 'CLC-klasse',
			total: 0
		}, {
			value: 'clk-klasse',
			label: 'CLK-klasse',
			total: 0
		}, {
			value: 'cls-klasse',
			label: 'CLS-klasse',
			total: 0
		}, {
			value: 'e-klasse',
			label: 'E-klasse',
			total: 0
		}, {
			value: 'g-klasse',
			label: 'G-klasse',
			total: 0
		}, {
			value: 'gl-klasse',
			label: 'GL-klasse',
			total: 0
		}, {
			value: 'gla-klasse',
			label: 'GLA-klasse',
			total: 0
		}, {
			value: 'glc-klasse',
			label: 'GLC-klasse',
			total: 0
		}, {
			value: 'gle-klasse',
			label: 'GLE-klasse',
			total: 0
		}, {
			value: 'glk-klasse',
			label: 'GLK-klasse',
			total: 0
		}, {
			value: 'gls-klasse',
			label: 'GLS-klasse',
			total: 0
		}, {
			value: 'm-klasse',
			label: 'M-klasse',
			total: 0
		}, {
			value: 'r-klasse',
			label: 'R-klasse',
			total: 0
		}, {
			value: 's-klasse',
			label: 'S-klasse',
			total: 0
		}, {
			value: 'sl-klasse',
			label: 'SL-klasse',
			total: 0
		}, {
			value: 'slc-klasse',
			label: 'SLC-klasse',
			total: 0
		}, {
			value: 'slk-klasse',
			label: 'SLK-klasse',
			total: 0
		}, {
			value: 'slr+mclaren',
			label: 'SLR McLaren',
			total: 0
		}, {
			value: 'sls+amg',
			label: 'SLS AMG',
			total: 0
		}, {
			value: 'sprinter',
			label: 'Sprinter',
			total: 0
		}, {
			value: 'v-klasse',
			label: 'V-klasse',
			total: 0
		}, {
			value: 'vaneo',
			label: 'Vaneo',
			total: 0
		}, {
			value: 'viano',
			label: 'Viano',
			total: 0
		}, {
			value: 'vito',
			label: 'Vito',
			total: 0
		}],
		// mg
		'mg': [{
			value: 'f',
			label: 'F',
			total: 0
		}, {
			value: 'tf',
			label: 'TF',
			total: 0
		}, {
			value: 'zr',
			label: 'ZR',
			total: 0
		}, {
			value: 'zs',
			label: 'ZS',
			total: 0
		}, {
			value: 'zt',
			label: 'ZT',
			total: 0
		}],
		// mini
		'mini': [{
			value: '1000',
			label: '1000',
			total: 0
		}, {
			value: 'cabrio',
			label: 'Cabrio',
			total: 0
		}, {
			value: 'clubman',
			label: 'Clubman',
			total: 0
		}, {
			value: 'countryman',
			label: 'Countryman',
			total: 0
		}, {
			value: 'coupe',
			label: 'Coupé',
			total: 0
		}, {
			value: 'mini',
			label: 'Mini',
			total: 0
		}, {
			value: 'paceman',
			label: 'Paceman',
			total: 0
		}, {
			value: 'roadster',
			label: 'Roadster',
			total: 0
		}],
		// mitsubishi
		'mitsubishi': [{
			value: 'asx',
			label: 'ASX',
			total: 0
		}, {
			value: 'carisma',
			label: 'Carisma',
			total: 0
		}, {
			value: 'colt',
			label: 'Colt',
			total: 0
		}, {
			value: 'eclipse',
			label: 'Eclipse',
			total: 0
		}, {
			value: 'galant',
			label: 'Galant',
			total: 0
		}, {
			value: 'grandis',
			label: 'Grandis',
			total: 0
		}, {
			value: 'i-miev',
			label: 'i-MiEV',
			total: 0
		}, {
			value: 'l200',
			label: 'L200',
			total: 0
		}, {
			value: 'lancer',
			label: 'Lancer',
			total: 0
		}, {
			value: 'outlander',
			label: 'Outlander',
			total: 0
		}, {
			value: 'outlander+sport',
			label: 'Outlander Sport',
			total: 0
		}, {
			value: 'pajero',
			label: 'Pajero',
			total: 0
		}, {
			value: 'pajero+pinin',
			label: 'Pajero Pinin',
			total: 0
		}, {
			value: 'pajero+sport',
			label: 'Pajero Sport',
			total: 0
		}, {
			value: 'space+runner',
			label: 'Space Runner',
			total: 0
		}, {
			value: 'space+star',
			label: 'Space Star',
			total: 0
		}, {
			value: 'space+wagon',
			label: 'Space Wagon',
			total: 0
		}],
		// morgan
		'morgan': [{
			value: '3+wheeler',
			label: '3 Wheeler',
			total: 0
		}, {
			value: '4',
			label: '4',
			total: 0
		}, {
			value: 'aero',
			label: 'Aero',
			total: 0
		}, {
			value: 'plus+4',
			label: 'Plus 4',
			total: 0
		}, {
			value: 'roadster',
			label: 'Roadster',
			total: 0
		}],
		// nissan
		'nissan': [{
			value: '100+nx',
			label: '100 NX',
			total: 0
		}, {
			value: '200+sx',
			label: '200 SX',
			total: 0
		}, {
			value: '300+zx',
			label: '300 ZX',
			total: 0
		}, {
			value: '350z',
			label: '350Z',
			total: 0
		}, {
			value: '370z',
			label: '370Z',
			total: 0
		}, {
			value: 'almera',
			label: 'Almera',
			total: 0
		}, {
			value: 'almera+tino',
			label: 'Almera Tino',
			total: 0
		}, {
			value: 'bluebird',
			label: 'Bluebird',
			total: 0
		}, {
			value: 'cube',
			label: 'Cube',
			total: 0
		}, {
			value: 'evalia',
			label: 'Evalia',
			total: 0
		}, {
			value: 'gt-r',
			label: 'GT-R',
			total: 0
		}, {
			value: 'juke',
			label: 'Juke',
			total: 0
		}, {
			value: 'leaf',
			label: 'Leaf',
			total: 0
		}, {
			value: 'maxima',
			label: 'Maxima',
			total: 0
		}, {
			value: 'micra',
			label: 'Micra',
			total: 0
		}, {
			value: 'murano',
			label: 'Murano',
			total: 0
		}, {
			value: 'note',
			label: 'Note',
			total: 0
		}, {
			value: 'nv200',
			label: 'NV200',
			total: 0
		}, {
			value: 'nv400',
			label: 'NV400',
			total: 0
		}, {
			value: 'pathfinder',
			label: 'Pathfinder',
			total: 0
		}, {
			value: 'patrol',
			label: 'Patrol',
			total: 0
		}, {
			value: 'pixo',
			label: 'Pixo',
			total: 0
		}, {
			value: 'primastar',
			label: 'Primastar',
			total: 0
		}, {
			value: 'primera',
			label: 'Primera',
			total: 0
		}, {
			value: 'pulsar',
			label: 'Pulsar',
			total: 0
		}, {
			value: 'qashqai',
			label: 'Qashqai',
			total: 0
		}, {
			value: 'serena',
			label: 'Serena',
			total: 0
		}, {
			value: 'sunny',
			label: 'Sunny',
			total: 0
		}, {
			value: 'terrano',
			label: 'Terrano',
			total: 0
		}, {
			value: 'x-trail',
			label: 'X-Trail',
			total: 0
		}],
		// opel
		'opel': [{
			value: 'adam',
			label: 'Adam',
			total: 0
		}, {
			value: 'agila',
			label: 'Agila',
			total: 0
		}, {
			value: 'ampera',
			label: 'Ampera',
			total: 0
		}, {
			value: 'antara',
			label: 'Antara',
			total: 0
		}, {
			value: 'ascona',
			label: 'Ascona',
			total: 0
		}, {
			value: 'astra',
			label: 'Astra',
			total: 0
		}, {
			value: 'calibra',
			label: 'Calibra',
			total: 0
		}, {
			value: 'cascada',
			label: 'Cascada',
			total: 0
		}, {
			value: 'combo',
			label: 'Combo',
			total: 0
		}, {
			value: 'corsa',
			label: 'Corsa',
			total: 0
		}, {
			value: 'frontera',
			label: 'Frontera',
			total: 0
		}, {
			value: 'gt',
			label: 'GT',
			total: 0
		}, {
			value: 'insignia',
			label: 'Insignia',
			total: 0
		}, {
			value: 'kadett',
			label: 'Kadett',
			total: 0
		}, {
			value: 'karl',
			label: 'Karl',
			total: 0
		}, {
			value: 'manta',
			label: 'Manta',
			total: 0
		}, {
			value: 'meriva',
			label: 'Meriva',
			total: 0
		}, {
			value: 'mokka',
			label: 'Mokka',
			total: 0
		}, {
			value: 'monza',
			label: 'Monza',
			total: 0
		}, {
			value: 'movano',
			label: 'Movano',
			total: 0
		}, {
			value: 'omega',
			label: 'Omega',
			total: 0
		}, {
			value: 'rekord',
			label: 'Rekord',
			total: 0
		}, {
			value: 'senator',
			label: 'Senator',
			total: 0
		}, {
			value: 'signum',
			label: 'Signum',
			total: 0
		}, {
			value: 'sintra',
			label: 'Sintra',
			total: 0
		}, {
			value: 'speedster',
			label: 'Speedster',
			total: 0
		}, {
			value: 'tigra',
			label: 'Tigra',
			total: 0
		}, {
			value: 'tour',
			label: 'Tour',
			total: 0
		}, {
			value: 'vectra',
			label: 'Vectra',
			total: 0
		}, {
			value: 'vivaro',
			label: 'Vivaro',
			total: 0
		}, {
			value: 'zafira',
			label: 'Zafira',
			total: 0
		}],
		// peugeot
		'peugeot': [{
			value: '1007',
			label: '1007',
			total: 0
		}, {
			value: '106',
			label: '106',
			total: 0
		}, {
			value: '107',
			label: '107',
			total: 0
		}, {
			value: '108',
			label: '108',
			total: 0
		}, {
			value: '2008',
			label: '2008',
			total: 0
		}, {
			value: '205',
			label: '205',
			total: 0
		}, {
			value: '206',
			label: '206',
			total: 0
		}, {
			value: '207',
			label: '207',
			total: 0
		}, {
			value: '208',
			label: '208',
			total: 0
		}, {
			value: '3008',
			label: '3008',
			total: 0
		}, {
			value: '306',
			label: '306',
			total: 0
		}, {
			value: '307',
			label: '307',
			total: 0
		}, {
			value: '308',
			label: '308',
			total: 0
		}, {
			value: '309',
			label: '309',
			total: 0
		}, {
			value: '4007',
			label: '4007',
			total: 0
		}, {
			value: '405',
			label: '405',
			total: 0
		}, {
			value: '406',
			label: '406',
			total: 0
		}, {
			value: '407',
			label: '407',
			total: 0
		}, {
			value: '5008',
			label: '5008',
			total: 0
		}, {
			value: '508',
			label: '508',
			total: 0
		}, {
			value: '605',
			label: '605',
			total: 0
		}, {
			value: '607',
			label: '607',
			total: 0
		}, {
			value: '806',
			label: '806',
			total: 0
		}, {
			value: '807',
			label: '807',
			total: 0
		}, {
			value: 'bipper',
			label: 'Bipper',
			total: 0
		}, {
			value: 'expert',
			label: 'Expert',
			total: 0
		}, {
			value: 'ion',
			label: 'Ion',
			total: 0
		}, {
			value: 'partner',
			label: 'Partner',
			total: 0
		}, {
			value: 'rcz',
			label: 'RCZ',
			total: 0
		}],
		// porsche
		'porsche': [{
			value: '718',
			label: '718',
			total: 0
		}, {
			value: '911',
			label: '911',
			total: 0
		}, {
			value: '918',
			label: '918',
			total: 0
		}, {
			value: '924',
			label: '924',
			total: 0
		}, {
			value: '928',
			label: '928',
			total: 0
		}, {
			value: '944',
			label: '944',
			total: 0
		}, {
			value: '968',
			label: '968',
			total: 0
		}, {
			value: 'boxster',
			label: 'Boxster',
			total: 0
		}, {
			value: 'cayenne',
			label: 'Cayenne',
			total: 0
		}, {
			value: 'cayman',
			label: 'Cayman',
			total: 0
		}, {
			value: 'macan',
			label: 'Macan',
			total: 0
		}, {
			value: 'panamera',
			label: 'Panamera',
			total: 0
		}],
		// renault
		'renault': [{
			value: '19',
			label: '19',
			total: 0
		}, {
			value: '21',
			label: '21',
			total: 0
		}, {
			value: '4',
			label: '4',
			total: 0
		}, {
			value: '5',
			label: '5',
			total: 0
		}, {
			value: 'avantime',
			label: 'Avantime',
			total: 0
		}, {
			value: 'captur',
			label: 'Captur',
			total: 0
		}, {
			value: 'clio',
			label: 'Clio',
			total: 0
		}, {
			value: 'espace',
			label: 'Espace',
			total: 0
		}, {
			value: 'fluence',
			label: 'Fluence',
			total: 0
		}, {
			value: 'kadjar',
			label: 'Kadjar',
			total: 0
		}, {
			value: 'kangoo',
			label: 'Kangoo',
			total: 0
		}, {
			value: 'koleos',
			label: 'Koleos',
			total: 0
		}, {
			value: 'laguna',
			label: 'Laguna',
			total: 0
		}, {
			value: 'master',
			label: 'Master',
			total: 0
		}, {
			value: 'megane',
			label: 'Mégane',
			total: 0
		}, {
			value: 'modus',
			label: 'Modus',
			total: 0
		}, {
			value: 'nevada',
			label: 'Nevada',
			total: 0
		}, {
			value: 'safrane',
			label: 'Safrane',
			total: 0
		}, {
			value: 'scenic',
			label: 'Scénic',
			total: 0
		}, {
			value: 'talisman',
			label: 'Talisman',
			total: 0
		}, {
			value: 'trafic',
			label: 'Trafic',
			total: 0
		}, {
			value: 'twingo',
			label: 'Twingo',
			total: 0
		}, {
			value: 'twizy',
			label: 'Twizy',
			total: 0
		}, {
			value: 'vel+satis',
			label: 'Vel Satis',
			total: 0
		}, {
			value: 'wind',
			label: 'Wind',
			total: 0
		}, {
			value: 'zoe',
			label: 'Zoe',
			total: 0
		}],
		// rolls-royce
		'rolls-royce': [{
			value: 'dawn',
			label: 'Dawn',
			total: 0
		}, {
			value: 'ghost',
			label: 'Ghost',
			total: 0
		}, {
			value: 'phantom',
			label: 'Phantom',
			total: 0
		}, {
			value: 'wraith',
			label: 'Wraith',
			total: 0
		}],
		// rover
		'rover': [{
			value: '100-serie',
			label: '100-serie',
			total: 0
		}, {
			value: '200-serie',
			label: '200-serie',
			total: 0
		}, {
			value: '25',
			label: '25',
			total: 0
		}, {
			value: '400-serie',
			label: '400-serie',
			total: 0
		}, {
			value: '45',
			label: '45',
			total: 0
		}, {
			value: '600-serie',
			label: '600-serie',
			total: 0
		}, {
			value: '75',
			label: '75',
			total: 0
		}, {
			value: '800-serie',
			label: '800-serie',
			total: 0
		}, {
			value: 'mini',
			label: 'Mini',
			total: 0
		}, {
			value: 'tourer',
			label: 'Tourer',
			total: 0
		}],
		// saab
		'saab': [{
			value: '9-3',
			label: '9-3',
			total: 0
		}, {
			value: '9-4x',
			label: '9-4X',
			total: 0
		}, {
			value: '9-5',
			label: '9-5',
			total: 0
		}, {
			value: '9-7x',
			label: '9-7X',
			total: 0
		}, {
			value: '900',
			label: '900',
			total: 0
		}, {
			value: '9000',
			label: '9000',
			total: 0
		}],
		// seat
		'seat': [{
			value: 'alhambra',
			label: 'Alhambra',
			total: 0
		}, {
			value: 'altea',
			label: 'Altea',
			total: 0
		}, {
			value: 'arosa',
			label: 'Arosa',
			total: 0
		}, {
			value: 'ateca',
			label: 'Ateca',
			total: 0
		}, {
			value: 'cordoba',
			label: 'Cordoba',
			total: 0
		}, {
			value: 'exeo',
			label: 'Exeo',
			total: 0
		}, {
			value: 'ibiza',
			label: 'Ibiza',
			total: 0
		}, {
			value: 'leon',
			label: 'Leon',
			total: 0
		}, {
			value: 'marbella',
			label: 'Marbella',
			total: 0
		}, {
			value: 'mii',
			label: 'Mii',
			total: 0
		}, {
			value: 'toledo',
			label: 'Toledo',
			total: 0
		}],
		// skoda
		'skoda': [{
			value: 'citigo',
			label: 'Citigo',
			total: 0
		}, {
			value: 'fabia',
			label: 'Fabia',
			total: 0
		}, {
			value: 'favorit',
			label: 'Favorit',
			total: 0
		}, {
			value: 'felicia',
			label: 'Felicia',
			total: 0
		}, {
			value: 'kodiaq',
			label: 'Kodiaq',
			total: 0
		}, {
			value: 'octavia',
			label: 'Octavia',
			total: 0
		}, {
			value: 'rapid',
			label: 'Rapid',
			total: 0
		}, {
			value: 'roomster',
			label: 'Roomster',
			total: 0
		}, {
			value: 'superb',
			label: 'Superb',
			total: 0
		}, {
			value: 'yeti',
			label: 'Yeti',
			total: 0
		}],
		// smart
		'smart': [{
			value: 'city-coupe',
			label: 'City-Coupé',
			total: 0
		}, {
			value: 'crossblade',
			label: 'Crossblade',
			total: 0
		}, {
			value: 'forfour',
			label: 'Forfour',
			total: 0
		}, {
			value: 'fortwo',
			label: 'Fortwo',
			total: 0
		}, {
			value: 'roadster',
			label: 'Roadster',
			total: 0
		}],
		// ssangyong
		'ssangyong': [{
			value: 'actyon',
			label: 'Actyon',
			total: 0
		}, {
			value: 'korando',
			label: 'Korando',
			total: 0
		}, {
			value: 'kyron',
			label: 'Kyron',
			total: 0
		}, {
			value: 'musso',
			label: 'Musso',
			total: 0
		}, {
			value: 'rexton',
			label: 'Rexton',
			total: 0
		}, {
			value: 'rodius',
			label: 'Rodius',
			total: 0
		}, {
			value: 'tivoli',
			label: 'Tivoli',
			total: 0
		}],
		// subaru
		'subaru': [{
			value: 'brz',
			label: 'BRZ',
			total: 0
		}, {
			value: 'forester',
			label: 'Forester',
			total: 0
		}, {
			value: 'impreza',
			label: 'Impreza',
			total: 0
		}, {
			value: 'justy',
			label: 'Justy',
			total: 0
		}, {
			value: 'legacy',
			label: 'Legacy',
			total: 0
		}, {
			value: 'levorg',
			label: 'Levorg',
			total: 0
		}, {
			value: 'mini+jumbo',
			label: 'Mini Jumbo',
			total: 0
		}, {
			value: 'outback',
			label: 'Outback',
			total: 0
		}, {
			value: 'svx',
			label: 'SVX',
			total: 0
		}, {
			value: 'trezia',
			label: 'Trezia',
			total: 0
		}, {
			value: 'tribeca',
			label: 'Tribeca',
			total: 0
		}, {
			value: 'vivio',
			label: 'Vivio',
			total: 0
		}, {
			value: 'wrx',
			label: 'WRX',
			total: 0
		}, {
			value: 'xv',
			label: 'XV',
			total: 0
		}],
		// suzuki
		'suzuki': [{
			value: 'alto',
			label: 'Alto',
			total: 0
		}, {
			value: 'baleno',
			label: 'Baleno',
			total: 0
		}, {
			value: 'celerio',
			label: 'Celerio',
			total: 0
		}, {
			value: 'grand+vitara',
			label: 'Grand Vitara',
			total: 0
		}, {
			value: 'ignis',
			label: 'Ignis',
			total: 0
		}, {
			value: 'jimny',
			label: 'Jimny',
			total: 0
		}, {
			value: 'kizashi',
			label: 'Kizashi',
			total: 0
		}, {
			value: 'liana',
			label: 'Liana',
			total: 0
		}, {
			value: 's-cross',
			label: 'S-Cross',
			total: 0
		}, {
			value: 'samurai',
			label: 'Samurai',
			total: 0
		}, {
			value: 'splash',
			label: 'Splash',
			total: 0
		}, {
			value: 'swift',
			label: 'Swift',
			total: 0
		}, {
			value: 'sx4',
			label: 'SX4',
			total: 0
		}, {
			value: 'vitara',
			label: 'Vitara',
			total: 0
		}, {
			value: 'wagon+r%2B',
			label: 'Wagon R+',
			total: 0
		}],
		// tesla
		'tesla': [{
			value: 'model+3',
			label: 'Model 3',
			total: 0
		}, {
			value: 'model+s',
			label: 'Model S',
			total: 0
		}, {
			value: 'model+x',
			label: 'Model X',
			total: 0
		}, {
			value: 'roadster',
			label: 'Roadster',
			total: 0
		}],
		// toyota
		'toyota': [{
			value: 'auris',
			label: 'Auris',
			total: 0
		}, {
			value: 'avensis',
			label: 'Avensis',
			total: 0
		}, {
			value: 'avensis+verso',
			label: 'Avensis Verso',
			total: 0
		}, {
			value: 'aygo',
			label: 'Aygo',
			total: 0
		}, {
			value: 'c-hr',
			label: 'C-HR',
			total: 0
		}, {
			value: 'camry',
			label: 'Camry',
			total: 0
		}, {
			value: 'carina',
			label: 'Carina',
			total: 0
		}, {
			value: 'celica',
			label: 'Celica',
			total: 0
		}, {
			value: 'corolla',
			label: 'Corolla',
			total: 0
		}, {
			value: 'corolla+verso',
			label: 'Corolla Verso',
			total: 0
		}, {
			value: 'funcruiser',
			label: 'Funcruiser',
			total: 0
		}, {
			value: 'gt86',
			label: 'GT86',
			total: 0
		}, {
			value: 'hilux',
			label: 'Hilux',
			total: 0
		}, {
			value: 'iq',
			label: 'iQ',
			total: 0
		}, {
			value: 'land+cruiser',
			label: 'Land Cruiser',
			total: 0
		}, {
			value: 'land+cruiser+100',
			label: 'Land Cruiser 100',
			total: 0
		}, {
			value: 'land+cruiser+v8',
			label: 'Land Cruiser V8',
			total: 0
		}, {
			value: 'mr2',
			label: 'MR2',
			total: 0
		}, {
			value: 'paseo',
			label: 'Paseo',
			total: 0
		}, {
			value: 'picnic',
			label: 'Picnic',
			total: 0
		}, {
			value: 'previa',
			label: 'Previa',
			total: 0
		}, {
			value: 'prius',
			label: 'Prius',
			total: 0
		}, {
			value: 'prius%2B',
			label: 'Prius+',
			total: 0
		}, {
			value: 'rav4',
			label: 'RAV4',
			total: 0
		}, {
			value: 'starlet',
			label: 'Starlet',
			total: 0
		}, {
			value: 'urban+cruiser',
			label: 'Urban Cruiser',
			total: 0
		}, {
			value: 'verso',
			label: 'Verso',
			total: 0
		}, {
			value: 'verso-s',
			label: 'Verso-S',
			total: 0
		}, {
			value: 'yaris',
			label: 'Yaris',
			total: 0
		}, {
			value: 'yaris+verso',
			label: 'Yaris Verso',
			total: 0
		}],
		// volkswagen
		'volkswagen': [{
			value: 'amarok',
			label: 'Amarok',
			total: 0
		}, {
			value: 'beetle',
			label: 'Beetle',
			total: 0
		}, {
			value: 'bora',
			label: 'Bora',
			total: 0
		}, {
			value: 'caddy',
			label: 'Caddy',
			total: 0
		}, {
			value: 'cc',
			label: 'CC',
			total: 0
		}, {
			value: 'corrado',
			label: 'Corrado',
			total: 0
		}, {
			value: 'crafter',
			label: 'Crafter',
			total: 0
		}, {
			value: 'eos',
			label: 'Eos',
			total: 0
		}, {
			value: 'fox',
			label: 'Fox',
			total: 0
		}, {
			value: 'golf',
			label: 'Golf',
			total: 0
		}, {
			value: 'golf+plus',
			label: 'Golf Plus',
			total: 0
		}, {
			value: 'golf+sportsvan',
			label: 'Golf Sportsvan',
			total: 0
		}, {
			value: 'jetta',
			label: 'Jetta',
			total: 0
		}, {
			value: 'lupo',
			label: 'Lupo',
			total: 0
		}, {
			value: 'new+beetle',
			label: 'New Beetle',
			total: 0
		}, {
			value: 'passat',
			label: 'Passat',
			total: 0
		}, {
			value: 'phaeton',
			label: 'Phaeton',
			total: 0
		}, {
			value: 'polo',
			label: 'Polo',
			total: 0
		}, {
			value: 'scirocco',
			label: 'Scirocco',
			total: 0
		}, {
			value: 'sharan',
			label: 'Sharan',
			total: 0
		}, {
			value: 'tiguan',
			label: 'Tiguan',
			total: 0
		}, {
			value: 'touareg',
			label: 'Touareg',
			total: 0
		}, {
			value: 'touran',
			label: 'Touran',
			total: 0
		}, {
			value: 'transporter',
			label: 'Transporter',
			total: 0
		}, {
			value: 'up',
			label: 'Up',
			total: 0
		}, {
			value: 'vento',
			label: 'Vento',
			total: 0
		}, {
			value: 'xl1',
			label: 'XL1',
			total: 0
		}],
		// volvo
		'volvo': [{
			value: '240',
			label: '240',
			total: 0
		}, {
			value: '340',
			label: '340',
			total: 0
		}, {
			value: '360',
			label: '360',
			total: 0
		}, {
			value: '440',
			label: '440',
			total: 0
		}, {
			value: '460',
			label: '460',
			total: 0
		}, {
			value: '480',
			label: '480',
			total: 0
		}, {
			value: '740',
			label: '740',
			total: 0
		}, {
			value: '760',
			label: '760',
			total: 0
		}, {
			value: '780',
			label: '780',
			total: 0
		}, {
			value: '850',
			label: '850',
			total: 0
		}, {
			value: '940',
			label: '940',
			total: 0
		}, {
			value: '960',
			label: '960',
			total: 0
		}, {
			value: 'c30',
			label: 'C30',
			total: 0
		}, {
			value: 'c70',
			label: 'C70',
			total: 0
		}, {
			value: 's40',
			label: 'S40',
			total: 0
		}, {
			value: 's60',
			label: 'S60',
			total: 0
		}, {
			value: 's70',
			label: 'S70',
			total: 0
		}, {
			value: 's80',
			label: 'S80',
			total: 0
		}, {
			value: 's90',
			label: 'S90',
			total: 0
		}, {
			value: 'v40',
			label: 'V40',
			total: 0
		}, {
			value: 'v50',
			label: 'V50',
			total: 0
		}, {
			value: 'v60',
			label: 'V60',
			total: 0
		}, {
			value: 'v70',
			label: 'V70',
			total: 0
		}, {
			value: 'v90',
			label: 'V90',
			total: 0
		}, {
			value: 'xc40',
			label: 'XC40',
			total: 0
		}, {
			value: 'xc60',
			label: 'XC60',
			total: 0
		}, {
			value: 'xc70',
			label: 'XC70',
			total: 0
		}, {
			value: 'xc90',
			label: 'XC90',
			total: 0
		}]
	}
}
