/**
 * Masterdata for options types
 */
export const options = {
	type: 'multiple',
	label: 'filters.masterdata.options.label',
	key: 'options',
	active: [],
	options: [{
		label: 'filters.masterdata.options.options.abs',
		value: 'abs',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.airbags',
		value: 'airbags',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.air_conditioning',
		value: 'air-conditioning',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.alarm',
		value: 'alarm',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.central_locking',
		value: 'central-locking',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.climate_control',
		value: 'climate-control',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.cruise_control',
		value: 'cruise-control',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.power_windows',
		value: 'power-windows',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.leather_furnishing',
		value: 'leather-furnishing',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.alloy_wheels',
		value: 'alloy-wheels',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.fog_lights',
		value: 'fog-lights',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.navigation_system',
		value: 'navigation-system',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.parking_sensors',
		value: 'parking-sensors',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.radio_cd',
		value: 'radio-cd',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.rain_sensor',
		value: 'rain-sensor',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.sunroof',
		value: 'sunroof',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.immobilizer',
		value: 'immobilizer',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.seat_heating',
		value: 'seat-heating',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.power_steering',
		value: 'power-steering',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.towbar',
		value: 'towbar',
		total: 0
	}, {
		label: 'filters.masterdata.options.options.xenon_lights',
		value: 'xenon-lights',
		total: 0
	}]
}
